table Sales
	lineageTag: d3319ea4-f2d1-49ae-8869-5191366195b1

	measure 'Sales Amount' = SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
		formatString: #,0.00
		lineageTag: 22f49b66-16ee-4044-bf38-c5172fe6ee24

	measure 'Total Orders' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: f55fa0cb-4271-4214-a759-03eb66f48047

	measure 'Total Customers' = DISTINCTCOUNT( Sales[CustomerKey] )
		formatString: #,0
		lineageTag: 8593b3c9-2406-40fe-aaea-276cfaeb33cb

	measure ShowValuesForDates = ```
			
			var max_date_available = CALCULATE(MAX( Sales[Order Date] ) , REMOVEFILTERS())
			var date_current_context = MIN('Date'[Date] )
			return 
			date_current_context <= max_date_available
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 61d3ed0a-7c89-4848-b1cc-8cbcdee6390f

	measure PreviousYearSales = ```
			
			var table_dates = CALCULATETABLE(DATEADD( 'Date'[Date] , -1 , YEAR )  , 'Date'[LastDateWithSales] = TRUE)
			return 
			IF( [ShowValuesForDates] , 
			    CALCULATE( Sales[Sales Amount] ,  DATEADD( 'Date'[Date] , -1 , YEAR )))
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bf577bb3-e29c-4061-9bee-a0c8a5bc8821

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Sales_difference_comparison = ```
			
			var current_year = Sales[Sales Amount] 
			var previous_year_sales = [PreviousYearSales] 
			var result = IF( not ISBLANK(current_year) && not ISBLANK(previous_year_sales) , 
			      current_year - previous_year_sales )
			      return 
			      result
			```
		formatString: #,0.00
		lineageTag: 16ecc4dc-b7bd-47ae-967f-cfb024df0130

	measure YearToDate_Sales =
			
			CALCULATE( Sales[Sales Amount] , DATESYTD( 'Date'[Date] ))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e50c80a5-4e1a-4525-9796-d9c39e92c870

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure PreviousYTD_Sales = ```
			
			var table_calculate =  CALCULATETABLE(DATEADD('Date'[Date] , -1 , YEAR ) ,  'Date'[LastDateWithSales] = TRUE)
			RETURN 
			IF( [ShowValuesForDates] , 
			CALCULATE( [YearToDate_Sales] , table_calculate ))
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f2bef7a8-1fb4-4e33-b871-8aaaf2882ff0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure CustomersWithMultipleOrders =
			
			var table_customer  = SUMMARIZECOLUMNS( Customer[CustomerKey] , "TotalOrders" , DISTINCTCOUNT(Sales[Order Number] ))
			RETURN
			COUNTROWS(
			FILTER( table_customer , [TotalOrders] > 1 )
			)
		formatString: #,0
		lineageTag: 13d798b3-fecf-402d-a0ec-b82c778aadc2

	column ProductKey
		dataType: int64
		isHidden
		lineageTag: e472b9fd-561d-4e93-8c32-3cd331541f17
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerKey
		dataType: int64
		lineageTag: 85e24fb8-5eb7-4ddf-b640-08e1b8e5cab0
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDateKey
		dataType: int64
		isHidden
		lineageTag: d2f77ac7-bd1c-4f6d-90a0-57a42eb78228
		summarizeBy: count
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Date'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: cb9b74f9-efa9-4cd3-9383-a5ac441537f3
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Delivery Date'
		dataType: dateTime
		isHidden
		formatString: mm/dd/yyyy
		lineageTag: 856eada8-4cc0-4550-8bbf-8586e742eba1
		summarizeBy: none
		sourceColumn: Delivery Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Order Number'
		dataType: string
		lineageTag: 7de2fac0-34ac-496d-9fb9-fb68a0e7da02
		summarizeBy: none
		sourceColumn: Order Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Order Line Number'
		dataType: int64
		isHidden
		lineageTag: c69546d7-d657-49a4-ae9e-aec91d216667
		summarizeBy: none
		sourceColumn: Order Line Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: f8430de8-03cf-4110-b769-718ddbfc139e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 7742cfa5-35e3-4064-a103-c1ab22006e4d
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

	column 'Unit Discount'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: fbf47a28-38af-4b18-bc4b-1d58decee5c6
		summarizeBy: none
		sourceColumn: Unit Discount

		annotation SummarizationSetBy = User

	column 'Unit Cost'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 78f0fbda-85e9-4b48-b910-fd0e72293ad8
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = User

	column 'Net Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 50030a66-00c1-462d-b452-b6a0193933d3
		summarizeBy: none
		sourceColumn: Net Price

		annotation SummarizationSetBy = User

	partition 'DaxBook Sales' = m
		mode: import
		source =
				let
				    Source = Sql.Database("Demo", "ContosoRetailDW"),
				    DaxBook_Sales = Source{[Schema="DaxBook",Item="Sales"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(DaxBook_Sales,{"OnlineSalesKey", "Due Date", "DueDateKey", "DeliveryDateKey", "CurrencyKey", "PromotionKey", "StoreKey"})
				in
				    #"Removed Columns"

		annotation IsQueryEditorUsed = False

		annotation QueryEditorSerialization

		annotation TableWidgetSerialization

	annotation _TM_ExtProp_QueryDefinition = SELECT * FROM [Sales]

	annotation _TM_ExtProp_DbTableName = 905

	annotation IsQueryEditorUsed = False

	annotation QueryEditorSerialization

	annotation TableWidgetSerialization

	annotation DataMarketWebBaseUrl

	annotation DataMarketWebQueryUrl

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

